services:
  superar1_educacion_continua:
    build: .

    container_name: superar1_educacion_continua

    restart: unless-stopped

    ports:
      - "8091:80"

    env_file:
      - .env

    volumes:
      - ./public/uploads:/var/www/html/public/uploads

    networks:
      - moodle_net

networks:
  moodle_net:
    external: true
